print "Starting maya loading and fbx conversion \n";
			
if (`file -q -exists "C:/Users/wilson/Desktop/paper/Paper/Assets/Models/PAPERP~1.MB"`)
{
	file -o "C:/Users/wilson/Desktop/paper/Paper/Assets/Models/PAPERP~1.MB";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "C:/Users/wilson/Desktop/paper/Paper/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

system ("del \"C:\\Users\\wilson\\Desktop\\paper\\Paper\\Temp\\CommandPipe\"");

$donepipeKill = `fopen "C:/Users/wilson/Desktop/paper/Paper/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
